# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_auto_20170921_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='latitude',
            field=models.FloatField(default=-20.297618),
        ),
        migrations.AddField(
            model_name='noticia',
            name='longitude',
            field=models.FloatField(default=-40.295777),
        ),
    ]
